language: generic

addons:
  ssh_known_hosts: siteground324.com:18765

after_success:
  # rsync deploy over ssh
  - set -e
  - openssl aes-256-cbc -K $encrypted_a54fd125a693_key -iv $encrypted_a54fd125a693_iv -in id_rsa_momentsforgrowth.enc -out "${TRAVIS_BUILD_DIR}/id_rsa_a1-server" -d
  - eval "$(ssh-agent -s)"
  - chmod 600 "${TRAVIS_BUILD_DIR}/id_rsa_a1-server"
  - ssh-add "${TRAVIS_BUILD_DIR}/id_rsa_a1-server"
  - rsync -avz -e "ssh -p 18765" --progress www yayfulli@siteground324.com:www/momentsforgrowth.com/moment
