language: generic

addons:
  ssh_known_hosts: siteground324.com:18765

before_deploy:
  # rsync deploy over ssh
  - set -e
  - openssl aes-256-cbc -K $encrypted_a54fd125a693_key -iv $encrypted_a54fd125a693_iv -in id_rsa_momentsforgrowth.enc -out /tmp/id_rsa_momentsforgrowth -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa_momentsforgrowth
  - ssh-add /tmp/id_rsa_momentsforgrowth

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz -e "ssh -p 18765" --progress www yayfulli@siteground324.com:www/momentsforgrowth.com/moment
  on:
    branch: master
